### ISSUE TITLE
Backend requires storing superuser postgre password in plaintext

### ISSUE THREAD

**Issue by 96jonesa** [aadijain725/AlgoWiz#70]
In the Developer Guide instructions for configuring postgreSQL, it says to place a password for a superuser postgre in the plaintext 'applications.properties' file. That is a serious security vulnerability - as a result, I can not build the backend.

**Comment by MadEste** [comment]
Looks like @wj01011 resolved in #92, should we also remove the tracking for this file @aadijain725 @praneshr2000 ?
