### ISSUE TITLE
Quiz Score

### ISSUE THREAD

**Issue by Oyestrone** [aadijain725/AlgoWiz#76]
After I submit an answer for the question, if I click on the choice again, it will resume to being in the state of unanswered. This is fine but when I finish the quiz, the score will overflow to 5/3. I don't think that's the expected behavior you wanted so you might want to fix that!

**Comment by aadijain725** [comment]
Yes, thank you for the report. We were able to fix that bug and will post it on the next push to main.

**Comment by aadijain725** [comment]
This has been resolved in the latest version of the app, thank you for the feedback :)
