### ISSUE TITLE
Quiz will not load

### ISSUE THREAD

**Issue by thornegarvin** [aadijain725/AlgoWiz#78]
When I try to navigate to the quizzes for all of the Algorithms, the app simply displays a loading bar and nothing happens.

Instructions for reproduction:

Navigate to public URL of project (https://aadijain725.github.io/AlgoWiz/#/AlgoWiz/)
Click on "Go To Quiz" for Binary Search

**Comment by aadijain725** [comment]
This has been resolved in the latest local version of the app, the online version will be coming soon :)
